### ISSUE TITLE
Reorganise l110n/Help for poeditor

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#102]
We have a free account with poeditor (https://poeditor.com/projects/view?id=214453) - which would allow us to find people to translate the app. I have most of the strings in from the L10N folder but what to do about the help pages? 
Not sure! ( I wonder if we move over to handlebars and a csv file?)

**Comment by willwade** [comment]
For the help pages - I wonder if we move over to [handlebars](http://handlebarsjs.com) and a csv file?

**Comment by hosseinamin** [comment]
The idea behind help page was to be able to change html structure for every language.

What i think is good to have.
1. A script to do conversion.
2. And writing help page as json (or po) format. And when it gets translated. We either use it as is. Like other pages. Or we can decide to change html structure and replace the text there (still x-l10n can work in other help files).

**Comment by willwade** [comment]
Yeah - needs a bit of a think this. Unlike the simple strings for the config page etc.. the help pages I can see needing a human to translate. Let's leave it for a while. I may add some of the parts to x-l10n and see how much works. The help pages need to settle down a bit before we tackle this.

**Comment by gavinhenderson** [comment]
Closing as im not sure if this is still applicable, can always re open if it is:
