### ISSUE TITLE
Allow user to attach specific settings to different trees

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#109]
Use case:
- Amir has a wife who is Arabic speaking only and carers who are English speaking only. 
- Amir needs Tree 1 to be in Arabic Cue/Arabic Main and Tree 2 to be Arabic Cue/English Main
- He can now switch (thanks to #69) but he has to get someone to change the TTS voices over. 

Right now the solution is to use recorded messages for output - but maybe the answer is somehow storing settings in the language tree (or a connected file).

**Comment by willwade** [comment]
would you have this as a meta-data or as some kind of comment?

**Comment by hosseinamin** [comment]
@willwade I suppose selection of speaker voice is not implemented well. We need to add locale to it.

And then within the tree locale will selected based on

1. select locale per node cue/main 
2. select locale for all cue/main

Something like this.

```
<meta data-cue-locale="ar"> <!-- meta at root would override default locale for all cue voices -->
- Say Hello <meta data-locale="es"> <!-- this will select `es` lang of cue and main for "Say Hello" -->
- Option 2 <meta data-main-locale="en-GB"> <!-- this will select `en` locale for cue voice for "Option 2" -->
```

Then voice selection at config would be per locale.

**Comment by willwade** [comment]
That sounds sensible. We may need more than locale though.. We may need either a name of the voice or some other identifier. I'm trying to track down all TTS voice details (https://docs.google.com/spreadsheets/d/17A8tos9-ARWjTrYCz-41C2yz9Ki7G4RtpTMLdOy-OUc/edit?usp=sharing) with locales etc. (The ones in Apples TTS is all from Acapella I understand)

**Comment by hosseinamin** [comment]
Yes. We can have locale and identifier per locale defined within the tree.

For example. UK voices have two speakers, male and female.

I can reorganize voice selection to fit this new design.

**Comment by hosseinamin** [comment]
At the moment i did implement use of locale per node and #122. Which provides tools for this issue. I did ignore ability to change config within a tree. It adds complexity. But i can see there's need for changing config for each tree. (graphical interface would be best for users). @willwade What do you think?

**Comment by willwade** [comment]
Yes - there is a need - I get your point though re: complexity and putting into the GUI. The problem is that for end users who actually use the app - they won't be able to access the config screens etc.. So they will need some way of switching. Maybe this needs more thought. Maybe we should/could create a way of loading config files e.g..
<meta data-default-config-file="some-file.xml/json/whatever">

It would then change the config settings in the config page.. Maybe????

Don't rush to do this - we can leave it if this needs more thought

**Comment by gavinhenderson** [comment]
@willwade I think this issue has been solved now that we can change the locales of trees? Feel free to re-open if you disagree
