### ISSUE TITLE
Message history window

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#119]
popup-message-wrp Is ok but really needs a constant display of what’s been written/ selected. Need:
- an option in config to turn on/off message display bar 
- if on, a small area at bottom of screen displays the words / letters being spelt (eg “I have something to say > chat > how are you?” 
- message area needs X at end to clear bar 
- also needs meta data action to clear it

Also for switch (keyboard) users:
- If turned on: Provide option in config as a helper "Scan message bar"
- If on, It will add the item to the Tree - either at the end or beginning of the tree. 
- Cue: "Message history" Main: Speak the main voice elements in the message area.

**Comment by willwade** [comment]
![Screenshot 2019-08-12 at 08 46 482](https://user-images.githubusercontent.com/229352/62851586-8f08f000-bcde-11e9-9621-02cf5b573296.png)

And 

![Screenshot 2019-08-12 at 08 46 483](https://user-images.githubusercontent.com/229352/62851672-caa3ba00-bcde-11e9-8fe2-58eb9e76efc3.png)

Some things to consider:

- Would show the last entry selected. If spelling keeps showing items. If single items - clears it when a new item selected. 
- Font size: Auto-fit to size - or fixed font size. The latter makes sense but not sure what should happen if text is longer than the area.

**Comment by hosseinamin** [comment]
About font size, I see fixed font size with multi-line capability works best.

**Comment by hosseinamin** [comment]
> also needs meta data action to clear it

Is the clear action going to remove the bar. Or is going to remove Its content.
As I've implemented so far. It looks like there is no need for this.
I'm going to publish my work soon. Maybe I got something wrong.

**Comment by willwade** [comment]
Just clear the content I was thinking
