### ISSUE TITLE
New interface/access method - scroll wheel to navigate. Switch/Key/LClick to select

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#121]
We have some users who can control a scroll wheel on a mouse. A totally different access solution is to use a scroll wheel (so scroll up/down - with a switch/keypress/left click to select). 

This obviously would only need to work on the Web version currently. 

I guess something like..

```$(function(){
    var _top = $(window).scrollTop();
    var _direction;
    $(window).scroll(function(){
        var _cur_top = $(window).scrollTop();
        if(_top < _cur_top)
        {
            _direction = 'down';
            // Activate/Hold down key
        }
        else
        {
            _direction = 'up';
            // Activate/Hold up key
        }
        _top = _cur_top;
        console.log(_direction);
    });
});​
```

Would this also work on iOS though if someone swiped up/down?

**Comment by hosseinamin** [comment]
Mouse wheel event is available. https://developer.mozilla.org/en-US/docs/Web/Events/wheel
And swipe is captured with touch events.
Apparently wheel event can capture wheels that support two axis movements.

**Comment by willwade** [comment]
Have some users where swipe is the main access method. Not sure if this fits here: Swipe Up/Down to navigate up/Down the tree and swipe left/right to access the tree elements. That would be neat
