### ISSUE TITLE
Voices on iOS to be listed by Locale and M/F

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#122]
On the web the voices are listed with their Locale - but on iOS they are just the long list. It would be great if they could be done with Locale on iOS..

e.g.

English, British
  - Susan (F)
  - Andy (M)
English, US
 - Someone (M)
 - Someone else (F)

etc.. 

To do this we may need to use this https://docs.google.com/spreadsheets/d/17A8tos9-ARWjTrYCz-41C2yz9Ki7G4RtpTMLdOy-OUc/edit#gid=0 - which I'm slowly pulling together

**Comment by hosseinamin** [comment]
iOS and web version both have their list within them. I know both considered having multiple locale.

With some tinkering this can be done on-the-fly.
