### ISSUE TITLE
Frontend Editor GUI

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#125]
To enhance the frontend editor I’ve been wondering about different interfaces. This seems an interesting idea to consider in the future : https://www.jointjs.com/ (I’m imagining that we would remove the quick edit feature and move all editing to a separate editing tab in settings where both the trees contents and order can be reorganised)

**Comment by gavinhenderson** [comment]
Closing just now, we do need to rethink the editor but we can open an issue when we have more of a plan
