### ISSUE TITLE
Switch press: Accept on release/ Accept on Down

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#127]
Currently if someone keeps a press of a key down - it can do odd things. We need a setting to accept the press on the down stroke of the key - or release of the key

**Comment by hosseinamin** [comment]
@willwade What do you mean by it does odd things? Is it only for iOS devices?

**Comment by willwade** [comment]
I’ll try and give a video of this. I don’t think it’s iOS only. Basically you press and hold the select key (eg right arrow) and it continually selects all items right. Is a long press one press or multiple presses? An option would be useful

**Comment by hosseinamin** [comment]
I did test it on web. It will only performs one action on release. It might be that iOS has issue with it.

**Comment by willwade** [comment]
It might be a Bluetooth keyboard thing. Let me see if I can replicate and I’ll share a video

**Comment by hosseinamin** [comment]
@willwade This is related to iOS. I've used UIKeyCommand to get keystroke events. And it does not give an option to detect press and release. I've to dig into iOS docs again. Maybe There's a solution for it.

**Comment by hosseinamin** [comment]
One practical solution for iOS would be to create a custom gatt bluetooth connection. And implement stuff we need for switch and probably speaker.

**Comment by willwade** [comment]
Closing this for now. Repeating presses now stopped by this: https://github.com/hosseinamin/pasco-cordova-plugin/commit/5a526815b1766bed8899ab7eb370b42b6efca8a6 - would still like to recognise down or up but not for iOS
