### ISSUE TITLE
New Option - Minimum cue:  Minimum time | All cue always | Off

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#133]
We are seeing a problem with some people new to auditory scanning and switching. They press the accept (right arrow) switch repeatedly and are not hearing the cue.. I've been thinking how to solve this. The debounce setting sort of helps but also doesnt.

I'm wondering if we could put in a new setting:

"Minimum Cue" Where there are three Options:
- Minimum Cue Time: 1-3000ms.  (Plays the cue for this time period before moving on)
- All cue always (default). (Plays the entire cue before moving on)
- Off (As it currently is)

NB: Presses won't be buffered if in the first two options. I.e. if you press your forward key whilst the cue is playing - ignore the key press.

**Comment by hosseinamin** [comment]
> NB: Presses won't be buffered if in the first two options. I.e. if you press your forward key whilst the cue is playing - ignore the key press.

For option two, How would one get when to press? Ignoring key press may not be a good practice. We already have ignore second key press. Maybe that can help.

**Comment by willwade** [comment]
> > NB: Presses won't be buffered if in the first two options. I.e. if you press your forward key whilst the cue is playing - ignore the key press.
> 
> For option two, How would one get when to press? Ignoring key press may not be a good practice. We already have ignore second key press. Maybe that can help.

Thats a good point. Maybe its just Option 1 or Off.

**Comment by willwade** [comment]
OK.. Finally getting 5 minutes to look at this! Looks great. I do think the Min quick time isnt working on iOS (& maybe web too now I take a closer look)

So I have it on "Minimum Cue time" 1300 and Manual. If I keep pressing the right arrow it will select the main on all items - I dont hear the cue. Expected: It should play the cue for a min of 1300 before moving on. 

Below is what might happen if a cue starts playing at 0 ms.. and lasts for 180ms. This is what I'm imagining..

Time    Keypress (right arrow key)      Do allow?  Min Time: 100ms
0  
10        Yes                                             No.
20
30       Yes                                             No.
40
 ..
120   Yes                                               Yes. 
180   (Sound stopped)


But what if the sound is < 100ms? I expect the min time = Sound Len in this situation.

And what about scan time. Lets imagine that it is 100ms scan rate. It *should* cut the cue off at 100ms.. and move on. Currently it doesn't (I haven't flagged this as a problem but maybe I should). In this case though Min Scan time (maximum amount) would = Max Cue time available in settings. 

so in settings maybe the answer is when a user changes the Scan time it affects the range of the Min Cue time. Lets say Automatic scan time they set to 100ms - Min Cue time - The maximum element on the slider is = 100ms. Or - we just ignore it and set it in the code to be that. What do you think? 

MinCueTime.Max = scan_time

**Comment by willwade** [comment]
This seems to be fine actually in iOS.. closing for now. Cheers @hosseinamin
