### ISSUE TITLE
Dividing communicator in two role plays (dispatcher and listener/moderator)

### ISSUE THREAD

**Issue by hosseinamin** [AceCentre/pasco#136]
By slicing communicator actions and user interfaces one can run the program in two device and connect them to co-operate.

1. split output voice
2. navigation on tree is done by dispatcher
3. ability to restart, change config/tree by listener/moderator
4. display screen for both roles

**Comment by willwade** [comment]
Just clarifying things - is #137 part of this - or different?

**Comment by gavinhenderson** [comment]
Closing in favour of #246
