### ISSUE TITLE
pair nodes via webrtc or websocket

### ISSUE THREAD

**Issue by hosseinamin** [AceCentre/pasco#137]
The role dispatcher starts accepting new connection with some requirements like password.
Listener/moderator goes into config and start a connection. (node discovery procedure is not defined at the moment)

Then when moderator is in the main page. It should sync what's state of dispatcher and is able to perform commands for modifying stuff in dispatcher.
Each role gets to have its own user interface. Meaning cue voice gets to run on dispatcher and main voice for moderator. (more config maybe needed)

**Comment by gavinhenderson** [comment]
Closing in favour of #246
