### ISSUE TITLE
Switches to be more easily configured

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#138]
The terminology is getting a bit confusing (we are detecting A,S,W,D, LEFT,RIGHT,UP,DOWN,SPACE,ENTER,B) - particularly in the config between space/enter. I wonder whether the user just has a dropdown of the letters they can choose for each action (Automatic: Select, Manual: 4 ways). ?

**Comment by willwade** [comment]
Ok - Think there is a problem.. maybe not detecting a hardware keyboard?  https://www.dropbox.com/s/cg2g2lqh3k1dero/IMG_0016.MOV?dl=0

**Comment by hosseinamin** [comment]
@willwade I did run into this issue as well. My last commit has bugfixes which will fix it. Are you sure the lastest `js/edit-config.js` has updated in the iOS build?
```
cd pasco
npm run cordova-dist
cd cordova
cordova build
```
