### ISSUE TITLE
<meta data-onselect-restart-in-branch-here>

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#14]
So Put automatic scanning on and try and spell a word using the alphabet

e.g.

  ` ## I shall spell it (spell)<meta data-onselect-restart-here>`

  ` ### a`

 `### b`

  ` ### c`

Its great - after selecting a letter it restarts in that menu. However the user has no way of escaping out and going to the top of the tree. So maybe one or both of these meta functions is required:

- `<meta data-onselect-restart-in-branch-here>` (so hitting a letter would restart in the level above) 
- `<meta data-onselect-go-up-level>` (so placing this at the end of the alphabet would allow user to go back a level). e.g.

`### z `

`### Go back <meta data-onselect-go-up-level>`

If we can have only one I vote for the last one!

**Comment by hosseinamin** [comment]
pressing left on navigation will go back. Can all users can do that?

**Comment by willwade** [comment]
No. Imagine you only had a keyboard and the space bar worked. E.g. https://m.youtube.com/watch?v=ewPzOmVEmow

**Comment by hosseinamin** [comment]
OK, got it.

**Comment by hosseinamin** [comment]
Maybe Stop/End is also needed.

**Comment by willwade** [comment]
Maybe. I'm trying to think it through. Would "back-a-level" do anything different to "end"?

**Comment by hosseinamin** [comment]
Yeah. that will work. I think it's simpler to have the terminate option. 
in that case we can concatenate selected letters and show it in the end.

**Comment by willwade** [comment]
Yeah - that would be very good.

**Comment by hosseinamin** [comment]
Estimated effort (EE)(time): 1-2H

**Comment by hosseinamin** [comment]
Done.
With these features. We can have a tree to perform row-column approach for faster selection. like.
```
# spell <meta data-onselect-continue-in-branch data-onselect-continue-concat>
## a to e
### a
### b
### c
### d
### e
## f to j
....
....
....
## Finish <meta data-onselect-finish>
```

**Comment by hosseinamin** [comment]
Here's some thought for improvement.

A new option to suggest until-now, like.
```
# spell  <meta data-onselect-continue-in-branch data-onselect-continue-concat="var_name,join_by">
## suggest <meta data-special-suggest="var_name">
## a
## b
## Finish
```

**Comment by hosseinamin** [comment]
NB: Naming these meta attributes are not easy.

**Comment by willwade** [comment]
Ok. This needs some more thought. You are right. We could get into meta-data hell.

**Comment by willwade** [comment]
Cool. So the text highlighted at the end is neat. A couple of things though:

- Remember this is largely for blind users. 
- The final "word" at the end needs to be in the main voice (and if not a word - just spelt out)
- After each letter - the user needs to hear the letters spelt so far (cue voice)

@hosseinamin - I realise this is quite a bit more work. Feel free to hold off any more on this for a bit

**Comment by hosseinamin** [comment]
@willwade Yeah. We're discovering ways to develop the current app.
