### ISSUE TITLE
Bug: Scan time not working

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#142]
Config:
Automatic Scanning: True
Loops: 3
Delay at first item: 400
Auto-scanning delay: 4800
Min Cue time: 100
Ignore Second hits: 1600

Setting these - or similar you an see the Auto-scanning delay isnt 4800 - its more like 1000 if not shorter.

**Comment by willwade** [comment]
https://www.dropbox.com/s/86qibclldu3i2l3/Video%2013-02-2019%2C%2009%2038%2008.mp4?dl=0

**Comment by hosseinamin** [comment]
fix #143
