### ISSUE TITLE
Record option currently broken 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#146]
You can’t record cues or main in the current release. https://www.dropbox.com/s/04y3qxwp4an40wl/Photo%2003-03-2019%2C%2007%2038%2008.jpg?dl=0

**Comment by hosseinamin** [comment]
That error may show up when iOS do not gave record permission to pasco. Make sure in settings record permission is given to pasco.

**Comment by willwade** [comment]
![screenshot 2019-03-04 at 09 29 37](https://user-images.githubusercontent.com/229352/53724877-c7b8b980-3e62-11e9-9c2d-d8cdb07304b5.png)
![img_3233](https://user-images.githubusercontent.com/229352/53724891-d1422180-3e62-11e9-942e-8d301c72ad75.PNG)

Hmm. Something else is wrong here. Not sure what
