### ISSUE TITLE
Problem with Type: / Paste: (Numbers becoming shifted. etc..)

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#150]
So I copy this text into the paste buffer running relayKeys on Windows:

https://paste.ee/p/FAEbB

And then we get this on the mac:

https://paste.ee/p/B6OJq

But whats really odd is that then, on the mac I cant type properly. Its like a Key is being held down.. Everything then comes to a halt. I can't send any more commands to relaykeys. Logfile isnt showing anything

So 3 Problems:
1. Numbers arent coming through. They are getting shifted. 
2. Something is going wrong as its stopping the sending of text
3. A keypress is getting stuck down.

**Comment by willwade** [comment]
Looking at this  - I'm wondering if something is going wrong with our board. Like a memory problem.. 

So relaykeys-cli is working but then it gets to a key and I'm getting a timeout on that key.. but its sending that one key over and over again.. 

https://www.dropbox.com/s/thcf8qakjtk113w/IMG_3240.MOV?dl=0
https://www.dropbox.com/s/2erxix87d8594iw/IMG_3241.MOV?dl=0

I then pull the board out, Plug it in again and it sends sending text - but its all garbled. Leave it a little bit longer and the text starts coming back in order again. 

https://www.dropbox.com/s/p9me7qp2rahmkd4/IMG_3242.MOV?dl=0

**Comment by hosseinamin** [comment]
This sounds like some sort of communication or memory issue. It can be an issue inside relaykeysd
