### ISSUE TITLE
Word prediction for letters in blocks

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#151]
This causes a nice little fault.. like it stops scanning. I think this cant be done because word prediction was meant to run for a-z. Would be nice if it did!

https://paste.ee/p/E0wUv

**Comment by hosseinamin** [comment]
This tree file has an issue. Instead of this. 
```
I will spell it
	<meta data-spell-branch  data-spell-update-dyn-onchange>
```

It should be this.

```
I will spell it<meta data-spell-branch  data-spell-update-dyn-onchange>
```

Also there's an issue when undo is used.

**Comment by hosseinamin** [comment]
@willwade If you perform the fix at my previous comment the issue will go away. This is not a bug. Instead a problem in tree itself.

**Comment by willwade** [comment]
Thanks! Sorry for the confusion 👍 https://paste.ee/p/PMlLl
