### ISSUE TITLE
"zero length"  / undefined error - on loading "Pragmatic Phrases" tree

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#152]
You can load the "Pragmatic Phrases" tree - but then you get an undefined error when it tries to play the tree. Looking in the js console its a zero-length error that its causing

**Comment by hosseinamin** [comment]
This template has a particular indentation at beginning of all lines. This is how it looks like.
```
(space)I have something to say
(space)(tab)Quick Messages
```

This is no good. Simple solution would be to remove first space from all lines.
This is a sign that the formatting We're using has ambiguity. And ended up with a tree without with zero nodes. (parser failed)
It would be best to move towards a standard. markdown is good. But Its ugly.
Using tabs and spaces are neat. Probably it should get standardized.
Something like. Spaces with no text will get treated as nothing. Or how many spaces needed in minimum, the default 4 spaces for each indentation, etc....
