### ISSUE TITLE
Changes to config screen..

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#160]
See: https://wireframe.cc/ETcUux
Layout to use something like this:

**Access**

- On-Screen Navigation (On/Off)
- Helpers
- Choose Access Method: Switch / Scroll  (Mouse/Touch) 
	- Switch Access
		- Choose: Automatic, Step (Was “Manual”) or  4-way (=using arrow keys in 4 directions). Similar options that already exist but also some tweaks! 
		
			1. In each we need a way of setting up the switches. Suggestion is to copy iOS’s way of selecting a switch for an acton.
			- Screen 1. Add New switch… 
			- Screen 2. “Activate your switch” and it will then record the keypress
			- Screen 3. “Set your action”. If Automatic: “Select” is the only option. If “Step” options are: “Select” or “Move"

			2. "Accept switch on release/down" See #127  - system wide option. Doesnt need to be for each switch. 

	- Scroll 
		
		Alert user that they need to scroll the screen with their finger or connect a USB/Bluetooh mouse and use the scroll wheel. 
		
		Option for selecting. Either: Left click / Tap or a switch press (If switch - go through options above to select switch). 

**Speech**

- Cue Voice
- Main Voice
	

**Appearance**

- Font Size 
- Theme 
- Locale

**Language**

- Active Tree
- Edit Tree
- Choose an example
- Tree management
- Import / Export 

Re: #7 #6 #121 #127

**Comment by hosseinamin** [comment]
> Choose Access Method: Switch / Scroll (Mouse/Touch) 

Switch and scroll can co-exist. It would be simpler to not have this option at all. Instead better documentation would help. And adding a checkbox for each to turn on/off the access method.
@willwade What do you think?

**Comment by hosseinamin** [comment]
But i allows us to have multiple behaviours if there's switch between these two access methods. It might be better to have this option.

**Comment by willwade** [comment]
Yeah - I realise it can run at the same time - I was thinking it may be useful to have this as a seperate option - particularly when you start choosing what the select option is going to be when using scroll.  Hmm.

**Comment by willwade** [comment]
NB: I'm hoping this in part fixes #74

**Comment by willwade** [comment]
NB: I'm trying to fix the switch configuration part from #138 - within this plan.

**Comment by willwade** [comment]
Totally forgot this is a rehash of #110  - see images in there for some other ideas..

**Comment by willwade** [comment]
Ok - finally got this on testflight Some small issues...!

1. On a small screen - Some of the settings pages are quite long and you need to scroll.. Is there a way of having a sub-menu? e.g "Main voice" | "Cue Voice" (and IF Auto-scan enabled) | "First time run Voice". Equally Access - I wonder if "Configure Actions" - should be in a sub-menu too? 
2. Getting a weird visual bug sometimes when hitting the radio buttons of Access Mode (see screenshot)
![IMG_1201](https://user-images.githubusercontent.com/229352/62036873-8d253400-b1ea-11e9-84fe-11e357181aea.PNG)
3. There's something amiss when moving from an already installed version with this one and the keystrokes (see screenshot). 
![IMG_1200](https://user-images.githubusercontent.com/229352/62036875-91515180-b1ea-11e9-9476-c15d97bbc8c1.PNG)

**Comment by hosseinamin** [comment]
@willwade 
>On a small screen - Some of the settings pages are quite long and you need to scroll.. Is there a way of having a sub-menu? e.g "Main voice" | "Cue Voice" (and IF Auto-scan enabled) | "First time run Voice". Equally Access - I wonder if "Configure Actions" - should be in a sub-menu too?

How about I add a sub-menu of sections just for mobile version. Which is scroll based. By clicking on a menu-item it will scroll to top of that section.

>Getting a weird visual bug sometimes when hitting the radio buttons of Access Mode (see screenshot)

I will look into it.


>There's something amiss when moving from an already installed version with this one and the keystrokes (see screenshot).

Have you used the latest version.

**Comment by hosseinamin** [comment]
>>

    There's something amiss when moving from an already installed version with this one and the keystrokes (see screenshot).

>Have you used the latest version.

One thing you need to keep in mind is that once you save with a pasco which has this bug. It will remain. But not for other users that use the bug-free version. (I did test it)

**Comment by willwade** [comment]
Re: "Have you used the latest version" - nope - the latest is now on testflight. My bad!

re: "How about I add a sub-menu of sections just for mobile version? Which is scroll based. By clicking on a menu-item it will scroll to top of that section." - yes - maybe thats a quick fix

**Comment by willwade** [comment]
Update: Latest version fixes the keyboard issue. Yay!

Sub-menus would be useful :)
