### ISSUE TITLE
Stay in Branch Helper in Config 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#164]
Some people want every page to have an action of "Stay in Branch" (which we implemented in #75 - Would be nice to have a helper option for this to apply to all branches

**Comment by hosseinamin** [comment]
I'm not sure how it would work. Can you elaborate?

**Comment by willwade** [comment]
If helper on, the app would apply the meta data action of stay-in-branch to all branches of the tree

**Comment by hosseinamin** [comment]
It will only be effective for nodes which have leaf node in them.  Is that the expected behaviour?
And they won't be able to start over. Expect adding a option to explicitly do that.

**Comment by willwade** [comment]
Yes. I *think* that’s right

**Comment by willwade** [comment]
Just to clarify. If they had back helper on AND this option then user has a back option to go back.
