### ISSUE TITLE
Long hold of switch - actions

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#166]
If user presses on the switch for x seconds we would like to detect this and create a new action.. E.g. "Back" or "Home" or "Stay on Current page" or "Say predefined message"

**Comment by hosseinamin** [comment]
Unfortunately with the API in iOS that I've used, Long press and hold cannot get implemented in iOS.

**Comment by willwade** [comment]
Yeah. I did figure that given all the issues we’ve had with keystrokes etc. For the future!

**Comment by willwade** [comment]
The answer to this is in a switch box. Closing for now
