### ISSUE TITLE
quick-setup.html

### ISSUE THREAD

**Issue by jasonnr** [AceCentre/pasco#179]
Hi have an issue with pasco

installed on a ipad2 with ios 9.3.5 however when  the app launches get error  "quick-setup.html undefined" and then the app does nothing i.e. white screen

try removing and reinstalling app but same issue

language is set to english   and region is set to united kingdom

  any ideas would be hugely appreciated

**Comment by willwade** [comment]
Woohoo! Thanks for this. Its fab getting these error reports from the Wild! Ok - well a new build is about to be released which may fix this - but if nothing else it may be easier to send these error messages.. I'm not sure why these appear - I've seen it randomly. 9.3.5 is a little old now but I don't think it should have anything to do with it..

@hosseinamin

**Comment by jasonnr** [comment]
Hi will

As well as the error message the app doesn’t work just get a blank white screen ?

Thanks

Jason

**Comment by willwade** [comment]
Hmm. That sounds really odd. Now I haven't seen that before.. Ok - if you can wait about a week hopefully the new one may fix this.. (but I have no idea what will be causing it.. @hosseinamin -  I'm wondering about better error tracking may be needed to hunt this kind of thing down.. )

**Comment by jasonnr** [comment]
Hi will

Is there any chance you can let me know when the new app is accessible via the app store

Thanks

Jason

**Comment by willwade** [comment]
Sure. Just testing it now. You can try it out too - I can pop your email address on TestFlight

**Comment by willwade** [comment]
Sign-up Here @jasonnr  - https://testflight.apple.com/join/HLOv7LB5  - thanks for helping!

**Comment by hosseinamin** [comment]
Upcoming version (It's now in TestFlight) of pasco has way better error reporting.
