### ISSUE TITLE
Voices not playing on Web

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#194]
Voices display  but no voice sound is heard - cues or main

**Comment by hosseinamin** [comment]
I've experienced the same thing on firefox. In my case firefox was disallowing playback of audio. When you click on left side of address-bar a drop-down will show up. You can check some settings for that site. Including playback settings.

**Comment by willwade** [comment]
Odd. I’m finding it in safari. Even after I get the warning to allow it to play audio

**Comment by willwade** [comment]
(This isn’t major of course)

**Comment by willwade** [comment]
I wonder if we should move to this in place of responsive voice on web. https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis 

This may help too. https://github.com/dasher-project/redash/commit/58e4519a0043ef77c3ec9d9633ee0a4cab23622a

**Comment by willwade** [comment]
If we moved to that it would solve TTS for  #84 too

**Comment by willwade** [comment]
closing for now

**Comment by hosseinamin** [comment]
Yes We can use html5 SpeechSynthesis instead of responsive-voice

**Comment by willwade** [comment]
@hosseinamin - been thinking about this. Do you think this would work in iOS build too? As I realise the web api default lists them when a language code which is handy (re: #122). It would also fix issue #86 on Windows and Mac if we ever ported it to that.

**Comment by hosseinamin** [comment]
As mozilla site points out. Yes.
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

**Comment by willwade** [comment]
Great. Can now use custom installed voices across any browser including Windows. Any chance we can pop the locale / language somehow into the dropdown? (ref: #122) (I'm not sure if we get aspects like Male/Female from the API). 

This maybe useful redash: https://github.com/dasher-project/redash/blob/master/browser/dasher/speech.js#L52 ![Screenshot 2020-03-31 at 11 43 14](https://user-images.githubusercontent.com/229352/78017928-ed094700-7344-11ea-8228-076d7a795891.png) (Although I'm not keen on the way its presented. The idea in #122 is neater if possible

**Comment by hosseinamin** [comment]
Yes. I'll add language to the name.
