### ISSUE TITLE
Need a initial training mode 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#198]
After the initial quick setup screen we need a way of stepping a user through how to use the app. Not sure how best to do this.

**Comment by willwade** [comment]
Maybe a quick video to be honest - that maybe the easiest thing to do - with a "Skip" button

**Comment by hosseinamin** [comment]
Right. I agree.

**Comment by willwade** [comment]
Great. Maybe just a simulator problem - but cant actually tap the "Skip" button when finished. 
Also - can we automatically advance once video finished?
<img width="354" alt="Screenshot 2020-03-31 at 09 11 01" src="https://user-images.githubusercontent.com/229352/78002946-d73d5700-732f-11ea-8281-de7e759cd67d.png">

**Comment by hosseinamin** [comment]
@willwade  I've added `core.js` to intro. It should fix the issue. On moving to next step after video has finished. I think it is better to keep it as is. Let me know what you think.

**Comment by willwade** [comment]
WW to make the video
