### ISSUE TITLE
Current node view gets shifted

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#202]
I can’t explain this easily. There is something a little frustrating about the display of nodes when navigating through the tree. 

When it first starts the tree is on the left. Then subsequent node you should see a > to indicate a previous branch. But this is sometimes text and >. The current central node shifts position as you go through it and it should be fixed. I think!

Not sure if this explains it. Look at spacing between current selected node and left hand side. In landscape this is even more dramatic. 

https://www.dropbox.com/s/ee9b9ajdz66uz99/Video%2009-02-2020%2C%2010%2023%2039.mp4?dl=0

**Comment by willwade** [comment]
<img width="382" alt="Screenshot 2020-02-17 at 22 41 46" src="https://user-images.githubusercontent.com/229352/74690399-e1b7ed00-51d6-11ea-8f2e-987cc9b8c63f.png">
<img width="367" alt="Screenshot 2020-02-17 at 22 41 55" src="https://user-images.githubusercontent.com/229352/74690402-e4b2dd80-51d6-11ea-9e0c-a9573f0f4f61.png">
<img width="375" alt="Screenshot 2020-02-17 at 22 42 08" src="https://user-images.githubusercontent.com/229352/74690404-e54b7400-51d6-11ea-8e92-e455ee6f5f5a.png">
<img width="370" alt="Screenshot 2020-02-17 at 22 42 31" src="https://user-images.githubusercontent.com/229352/74690405-e5e40a80-51d6-11ea-8269-e3f877cf2a43.png">

**Comment by willwade** [comment]
Need to check this. I think its fixed - but from a quick look on a mobile device you now lose the left hand arrow when in a child node. You don't see any back arrow at all.

**Comment by hosseinamin** [comment]
> Need to check this. I think its fixed - but from a quick look on a mobile device you now lose the left hand arrow when in a child node. You don't see any back arrow at all.

I can reduce width of the list to something like 80% , Which can show back arrow.

**Comment by willwade** [comment]
That might do it
