### ISSUE TITLE
New appearance setting - alter message bar height 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#207]
Ideally want several sizes - one that is nearly full screen and allows for just one line above it, One that is a third height - and one that is what it currently is. Remind me is message bar themeable? I need to add some tweaks for the themes for message bar - e.g. high contrast

**Comment by hosseinamin** [comment]
Yes, Almost all elements in the body tag are theme-able.

**Comment by willwade** [comment]
Thanks. I guess initally I was thinking we would have this as a configuration option - but having it themable (i.e the colour of the background message bar and font) would be useful.

**Comment by willwade** [comment]
Re #208 - Somewhat a duplication now. Leaving open but can close this one when the other is finished
