### ISSUE TITLE
Move "Display message bar when spelling" to Appearance

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#208]
Feels more accurate putting that in appearance than in helpers

**Comment by willwade** [comment]
Not sure if we have introduced this bug - but Message bar now displays even if "Display message bar when spelling" is not checked

**Comment by willwade** [comment]
See video: 
https://www.dropbox.com/s/tufdllbnmojs0vr/Screen%20Recording%202020-03-31%20at%2009.25.33.mov?dl=0

Some probs:
1. Watch how I tap UP and it rightly goes to the bottom of the list. I tap up again and it gets stuck (I was trying to get to undo)

See video 2:
- 1. So after selecting a prediction I was expecting "Control" to end with a space - and it then restart. But it doesnt. I need to enter a space manually
- 2. Notice how I repeatedly tap down - and it actually then hangs

Not sure how big a problem this is - but in the logs I see:

```2020-03-31 09:25:11.879543+0100 pasco[2173:2358630] WARN: Could not load trees_info file, cdvfile://localhost/persistent/trees-info.json Error: Fail to load `cdvfile://localhost/persistent/trees-info.json` -- 1``` (maybe not related)

- One last thing(!). Is it possible under "Message Bar height" to have "Font Size for Message bar" - % slider?

**Comment by hosseinamin** [comment]
I've recently pushed a new commit. Which did fix a problem like that for me. Please check if it does fix these issues.

**Comment by willwade** [comment]
I *think* its still there.. 
https://www.dropbox.com/s/kxh8jdzdi6f4c9k/Screen%20Recording%202020-04-01%20at%2009.04.32.mov?dl=0

**Comment by willwade** [comment]
Ok - all fixed. Just one small thing outstanding..

> Is it possible under "Message Bar height" to have "Font Size for Message bar" - % slider?

To be clear - I'm not sure if this is best done as a % change - basically need to change the font height - but maybe best done as a theme thing - and not sure what happens to lines or line height and spacing..  Maybe % change will do it.
