### ISSUE TITLE
Option to turn on/off switch holding down

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#210]
#127 fixed a really horrible problem. But we now have people who want to press and hold - and it then quickly scan through each item. Is there a way of turning on/off the fix in a config option (Under Access )??

**Comment by hosseinamin** [comment]
yes

**Comment by willwade** [comment]
Nice. Lets name it "Allow hold down of switches". With help text of "Allows holding down a switch/key to repeat the action quickly". And move below "Configure Actions"

Not sure how big a deal this is but see screenshot of overlapping text. Maybe not a problem when we move it.

<img width="343" alt="Screenshot 2020-03-31 at 09 17 31" src="https://user-images.githubusercontent.com/229352/78003508-ac9fce00-7330-11ea-9b1f-fe98da80ce83.png">
<img width="333" alt="Screenshot 2020-03-31 at 09 15 45" src="https://user-images.githubusercontent.com/229352/78003511-ad386480-7330-11ea-8125-b72633f00173.png">
