### ISSUE TITLE
Non responsive when click/tap before audio finished

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#217]
Video: https://www.dropbox.com/s/cd8mg5dgmjixn6q/Screen%20Recording%202020-04-20%20at%2012.36.20.mov?dl=0

Use  pasco and tap on the navigation arrow to move through the tree. If you tap before the audio finished of one item it stops responding to any input. The bug occurs in Chrome/Safari/Firefox on iOS and MacOS.

**Comment by willwade** [comment]
This maybe due to using the html speech synthesis api. It’s experimental. https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices

**Comment by willwade** [comment]
Note - doesn’t happen on the Cordova - iOS - version of the app. Not sure why there would be thus discrepancy (but no bad thing as currently iOS is our primary target - going forward would be nice to fix if we move to Android/windows/raspberry pi builds etc)

**Comment by willwade** [comment]
Looks to me like this is now fixed - but by an upgrade in Safari and Chrome.. doesn't appear to be happening any more!

**Comment by hosseinamin** [comment]
I can't replicate this issue on Safari of macos Big Sur.
