### ISSUE TITLE
No voices in Chrome

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#218]
![Screenshot 2020-04-20 at 12 42 18](https://user-images.githubusercontent.com/229352/79747951-75578800-8304-11ea-90b7-7cd9cf7f4e87.png)

Strange this one. Voices are appearing in Safari and Firefox.

**Comment by gavinhenderson** [comment]
I've done some digging into this.

It seems to me like its because `speechSynthesis.getVoices()` returns an empty array on chrome but not on safari on firefox.

Specifically on this line: https://github.com/AceCentre/pasco/blob/a9b4d53098be71293d2a702aff4ab42a17c9d451/html/js/core.js#L1172

**Comment by gavinhenderson** [comment]
Apparently it takes a while for the voices to be populated on chrome so you have to wait awhile before requesting the voices. Happy to try and make a fix and open a PR?

**Comment by gavinhenderson** [comment]
Got a fix working locally, will fork and submit a PR

**Comment by willwade** [comment]
Thanks! That’s awesome :)
