### ISSUE TITLE
Move from Bower to Webpack

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/pasco#221]
Bower is no longer getting new feautes and their official line is:

> While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!

Using webpack will enable lots of positive changes to the codebase which will increase maintainability and make it quicker to implement new features.

As an open source project using modern technology also makes the project more approachable to more developers.

Using webpack would also enable discussion around using modern front end frameworks

I'm happy to do the work to migrate.

**Comment by willwade** [comment]
Yeah by all means! Sounds good to me! It’s yours!

**Comment by willwade** [comment]
Parking this for now.. @gavinhenderson I'll let you pick this up again in good time.. :)

**Comment by gavinhenderson** [comment]
@willwade We have come full circle!

Although i am going to close this, 2 years later i have better plans
