### ISSUE TITLE
Importing a backup from URL

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#228]
Having some problems helping clients open and restore zip backups that we’ve created. Not sure best approach - maybe using something like [universal links plugin](https://www.npmjs.com/package/cordova-universal-links-plugin)?

**Comment by hosseinamin** [comment]
Good idea, no need for that plugin. We can simply download the file and put it in the import task.

**Comment by hosseinamin** [comment]
qrcode reader can help here.

**Comment by willwade** [comment]
So how would that work? We pop a file somewhere online & generate a qr code for it. Then they scan the QR code - it takes them to a browser - and the browser opens pasco app and imports?

**Comment by willwade** [comment]
See also #89

**Comment by hosseinamin** [comment]
Well, I was thinking for when the app is open already and they click on import with url. Then a dialog comes up with url text box and a qrcode reader button.
There's also the ability to create a protocol lets say, pascorestore://...
Which will open the pasco app and import directly by translating the url to https.

**Comment by willwade** [comment]
Got you. So two techniques to implement:

1. Register a unique URL path in-app. Add an event handler to then download stream and put in import task. 
2. Add "Import URL" alongside file browser to "Import" which then shows QR/URL field.

**Comment by hosseinamin** [comment]
Right.

**Comment by willwade** [comment]
Interestingly this seems that the URL protocol is a little outdated - https://stackoverflow.com/a/11421402/1123094 - but whatever - I think we know what roughly we want it to do to work.

**Comment by willwade** [comment]
Hmm.. 

I'm starting to wonder if this is better just dealt by making sure we have https://github.com/cowbell/sharedrop https://www.sharedrop.io/ - installed or bookmarked on the device.. Would be nice to integrate an import/export of sharedrop into pasco of course (or our own fork of it)..

**Comment by gavinhenderson** [comment]
Closing in favour of #89
