### ISSUE TITLE
Add facial gestures as switch options

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#231]
This would be nice to try out. 

https://github.com/open-aac/cordova_face#supported-features

We don't want to use face tracking - but gestures to use as switch options

Something like this:

![Screenshot 2020-06-24 at 10 56 32](https://user-images.githubusercontent.com/229352/85534787-8759ed80-b609-11ea-8724-31076f762e88.png)

Where the user then selects one of:

"wink"
"smirk"
"smile"
"mouth_opeen"
"kiss"
"tongue"
"puff" (puff out cheeks)
"eyebrows"

**Comment by gavinhenderson** [comment]
Closing as we can fix this by adding an android build (#84 ) which has facial gestures built in
