### ISSUE TITLE
Create meta tag to change make pronunciation different to display

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#239]
Some words are said by the text to speech engine badly

We need to create a pronunciation editor..

Something like this:![](https://www.assistiveware.com/uploads/article/_articleImageSmall/1.4.3-1-EN.PNG)

One tweak to this - it can be hard remembering the IPA alphabet.. (see [here](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#supported-symbols) for what that looks like) and how to write with it. So I wonder converting the spoken text to IPA format - for someone then to edit.  Something like this app is doing: https://tophonetics.com 

Maybe - this helps.. https://developer.apple.com/documentation/avfoundation/avspeechsynthesisipanotationattribute?changes=latest_beta

Looks like this is the API on iOS we would have to use: https://developer.apple.com/documentation/appkit/nsspeechsynthesizer/1448500-phonemesfromtext

**Comment by gavinhenderson** [comment]
@willwade Pretty sure this is an old issue that we now have? We can do this by overriding the main and cue label and spelling it phonetically? Okay if I close this issue?
