### ISSUE TITLE
Support Spotify playback and interaction

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#241]
Allow user to navigate Spotify within Pasco. 

For example the tree might list all of the latest playlists and allow the user to select a playlist.

Helpful links:
* https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/
* https://developer.spotify.com/documentation/web-api/reference/

**Comment by gavinhenderson** [comment]
@willwade I would suggest that before we do this we should create a 'plugin ecosystem' which makes a very clean API to allow for programtic control of a tree.

This would mean we can add plugins like a spotify plugin really easily, but it also means we dont clutter the settings with spotify options for users unless they enable the spotify plugin.

It will also give us scope to add other spotify competitors

**Comment by gavinhenderson** [comment]
Closing in favour of #286
