### ISSUE TITLE
Backup / restore vocabulary online

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#243]
So a “sync with Dropbox “ button. Hitting that signs you in and uploads all the trees the user has - not just the active one. Any edits then the vocabulary gets resaved. On a different device - if someone signs in using the same Dropbox account it pulls the data in. Going forward there would need to be a button of “update from Dropbox” but show this only if the version in Dropbox is timestamped newer than the devices vocabulary. 

NB. Dropbox or gdrive or other. Happy to look at options.

**Comment by hosseinamin** [comment]
I suggest to add some parameters in the config to select which folder to look for and authorization with the provider.
With this it be managed easier. And there's no need to login with same account.

**Comment by hosseinamin** [comment]
@willwade We may need to spin up a server for dealing with authorization with dropbox or google drive.

For oauth2 authorization method a server is required. Though I can see dropbox has a simple method for generating access token for the account owner. If you want to use that it will not be a convenient process.
