### ISSUE TITLE
Word prediction using mozolm

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#252]
We should definitely try and integrate an offline version of the PPM model of Mozolm http://github.com/google-research/mozolm

**Comment by willwade** [comment]
There is a problem with Mozolm. Its heavy handed for this - and not multi language. A first attempt might be to improve our prediction engine using a PPM method: https://github.com/dasher-project/dasher-web/blob/4df83dda60dcda9591aad36d9dd3b9a03ff4fcd1/browser/dasher/predictor_ppm.js

**Comment by gavinhenderson** [comment]
Closing this in favour of #251

We should make our current prediction better before we need to look at using mozolm
