### ISSUE TITLE
Spelling not working

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#259]
# Reproduction Steps

- Load up Spell by Letter/Word prediction Tree
- Set as active tree
- Turn on Appearance - Display message bar when spelling
- Try and spell. It doesnt

# Platform

Testing this on Safari. Maybe a problem elsewhere.

**Comment by gavinhenderson** [comment]
Happens on safari and on the app, so it must be a webkit issue.

**Comment by gavinhenderson** [comment]
@willwade This seems to work again so I am going to close this issue
