### ISSUE TITLE
Config: drop down with default trees (markdown files). 

### ISSUE THREAD

**Issue by willwade** [ACECentre/pasco#26]
A drop down available in the config before the language section which would allow a user to load up different default files. E.g.

- Adult - care needs
- Adult - general chatting
- Child - Starting off auditory scanning 

Selecting would put contents in the markdown text area.

**Comment by hosseinamin** [comment]
I will add the ability for users to add or delete entry.

**Comment by willwade** [comment]
No need for users to add / remove - just for us to predefine a load of different options.

**Comment by willwade** [comment]
Example trees: https://github.com/ACECentre/pasco/tree/master/html/trees 
NB: I've labelled these xx-Name_Of_file.md where xx is the lang code. Underscores are expected to be spaces. If you have a better naming convention then go for it ;)
