### ISSUE TITLE
A way of turning on / off main cues. 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#261]
Some users dont need all their navigation (tree elements) read out loud..

- So right now way to do this is record a blank wav file for Main. 

- Going forward we could have an option of "Dont read out Main until last selection" 

- Or we set as a meta-data action of "dont read aloud"

**Comment by gavinhenderson** [comment]
@willwade  Doing `<meta data-auditory-cue=" ">` seems to solve this now? You will have to add it for each item though.

Note you have to use put a space between the quotes and not just nothing otherwise it reads out the word as the cue

Does that solve this issue?

**Comment by willwade** [comment]
yeah - enough for now
