### ISSUE TITLE
Support more voices in more languages

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#280]
Re: Voice Broker

Also 

- Code Factory - Nuance Vocalizer Expressive Text to Speech (codefactoryglobal.com) |
- https://murf.ai/text-to-speech 
- https://play.ht 
- https://voicemaker.in 
- https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/how-to-speech-synthesis?tabs=browserjs%2Cterminal&pivots=programming-language-csharp

**Comment by gavinhenderson** [comment]
Going to close this in favour of  #86
