### ISSUE TITLE
Create a onboarding experience

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#281]
Onboarding/Intro experience could be improved. Notably for editing as well as playing

**Comment by gavinhenderson** [comment]
@willwade I think the onboarding experienced would be much improved if we were to improve the settings UI and editing flow on Pasco as a whole, which would filter through to the onboarding experience. 

With that in mind do you mind if I repurpose this issue to be a UI issue for settings + vocab? (will likely split it up)
