### ISSUE TITLE
Spelling - Basic implementation

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#38]
(NB: note similarities to discussion from #14 )

When we work with indviduals on paper this is usually done by:

1 . "A to H", "I to M", "N to Z" (or a different arrangement of letters). The user selects the block they want e.g. "A to H?" "Yes". 
2. And then the partner says "A, B , C, D, E, F, G, H". The user selects the letter
3. And the partner reads out the letters selected e.g. "H e". 

If the user finishes the branch there it will say out "He". 

That would be the simplest mode of operation I think we need.

**Comment by willwade** [comment]
this is nearly right..

`## I shall spell it (spell)<meta data-onselect-continue-in-branch data-onselect-continue-concat>

### a to h

- a

- b

- c

- d

- e

- f

- g

- h

### i to r 


- i 

- j

- k

- l

- m

- n

- o

- p

- q

- r


### s to z


- s

- t

- u

- v

- w

- x

- y

- z


### Finish <meta data-onselect-finish>
`

Whats needed though. 
1. `<meta data-onselect-finish>` needs to read it aloud - not just display it. It should read it as a whole word
2. After each letter selected have a way of spelling out the letters selected so far. E.g. If I was spelling Hossain - and I do Ho - it would say "H O". I guess this needs to be a new meta tag.

**Comment by hosseinamin** [comment]
Done, 
Meta attributes have changed to.
```
<meta data-spell-branch>
# Finish <meta data-spell-finish>
```

Root of tree can have meta tag. I changed default trees so they can be more efficient.

**Comment by willwade** [comment]
Awesome.
