### ISSUE TITLE
Idea: meta-data-action-webhook-post (and maybe webhook-get?)

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#41]
Just an idea..

On selecting an item with a meta-data-action-ifttt:command - selecting the item would trigger a IFTTT request (https://ifttt.com/maker_webhooks)

**Comment by hosseinamin** [comment]
Great idea. I love to see how that plays out.

**Comment by willwade** [comment]
Ifttt is nice and simple but costs developers. Maybe supporting Zapier would make sense too  https://zapier.com/page/webhooks/

**Comment by willwade** [comment]
Also ideally support homebridge- https://www.npmjs.com/package/homebridge-http-webhooks (we would typically trigger items so we would at least need the section heading “trigger change for Boolean accessory”)

**Comment by willwade** [comment]
Maybe the answer is a generic webhook action.. Or two - one that posts and one that receives (Result would be read aloud). Still though - I see a problem in that each provider has a different format for posting and responding. Unless of course pasco cleverly figured out which service is which and dealt with it appropriately.

**Comment by hosseinamin** [comment]
I like the idea. Integration with multiple services is not a concern. We need to find the one which provides the most with least cost. I like the idea of running a home server.
