### ISSUE TITLE
Ideas for new config

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#43]
Not enjoying the way the menus are activated. Because we have so few options I'm toying with a UI that looks like this. Thoughts?

<img width="745" alt="screen shot 2018-03-20 at 00 33 30" src="https://user-images.githubusercontent.com/229352/37629424-9668aa1a-2bd6-11e8-948b-8fbd0308335f.png">
<img width="389" alt="screen shot 2018-03-20 at 00 33 10" src="https://user-images.githubusercontent.com/229352/37629425-967f56ca-2bd6-11e8-94d8-006c93e3b82d.png">
<img width="362" alt="screen shot 2018-03-20 at 00 30 47" src="https://user-images.githubusercontent.com/229352/37629426-9695af2e-2bd6-11e8-9c17-5a3e6590d4ab.png">

**Comment by hosseinamin** [comment]
All good.

**Comment by hosseinamin** [comment]
Probably we need to use Creative Common Licensed icons. If you have figured it out already. Please share links to these icons.

**Comment by paulhewett** [comment]
These were from fontawesome (is that CC?). Needs a bit more work. Edit symbol not right. Move play symbol to right hand side. (almost like the close button of the window). Will work on a little more.

**Comment by hosseinamin** [comment]
@paulhewett Yes, https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt

**Comment by willwade** [comment]
Think this is a bit better for the small view. For the expanded view still thinking of text with Symbols as above (but in this order).

Other tweaks:

- [ ] "Configuration" Should be Settings

"Play" Front screen: 
![img_0885](https://user-images.githubusercontent.com/229352/37648833-fe2a3fbe-2c27-11e8-8ea5-6c88b0d09997.jpg)


Settings:
![img_0887](https://user-images.githubusercontent.com/229352/37648831-fdc7e92c-2c27-11e8-9a21-7ab6bfec538f.jpg)

"Edit" Screen:
![img_0886](https://user-images.githubusercontent.com/229352/37648834-fe424244-2c27-11e8-9b28-c323558bcc52.jpg)
