### ISSUE TITLE
change pasco to source sans pro

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#45]
For the "pasco" in the header it would be nice if either an image or using text using font source sans pro: http://pasco.chat -
https://fonts.google.com/specimen/Source+Sans+Pro

**Comment by hosseinamin** [comment]
I want to store fonts locally. @willwade Which fonts we want to use?
Here i found a place to download it.
https://www.fontsquirrel.com/fonts/source-sans-pro?q[term]=Source+Sans+Pro&q[search_check]=Y

**Comment by willwade** [comment]
Good question. Can you work it out from heading seen here https://pasco.chat
