### ISSUE TITLE
Format of language file..

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#46]
I realise this may be dramatic but...

I'm wondering before we go much further the format of the language tree needs to change. Reason being I'm now thinking this: https://gist.github.com/willwade/8a91165148bf537ad34233b82a4f78fb is easier to read than https://raw.githubusercontent.com/AceCentre/pasco/master/html/trees/en-GB-Pragmatic_Phrases.md 

@hosseinamin - how hard would it be to cope with this change? Too hard? 

(NB: This is a nice bit of ruby that converts the markdown trees we already have to this format: https://gist.github.com/willwade/2c771fdcb4adfc0c1588324bf59c4d11 - from http://brettterpstra.com/2013/08/18/markdown-to-mind-map/)

**Comment by hosseinamin** [comment]
It's not too hard. Though we have meta tag. Is that would be the same?

**Comment by willwade** [comment]
Yes. I can see us keeping the meta tag

**Comment by hosseinamin** [comment]
If markdown's syntax is fine with you. We can apply indentation, including `# - *`

**Comment by willwade** [comment]
So would files be parsed with or without markdown. Ie. If markdown use that. If indentation use that. A bit like that script I noted above ?

**Comment by hosseinamin** [comment]
If it modifies indentations to hashtag before running the parser, md and indent based can be parsed with current code.

**Comment by hosseinamin** [comment]
So. Yes. It's simple to do.
