### ISSUE TITLE
Bug: index.html - failure!

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#47]
Getting this bug on the [current build](https://github.com/AceCentre/pasco/commit/38d69dc8ac01366cef59abfc5f1087e9fc61ebfa) of the iOS version. All works but can't access any of the child nodes. This alert appears when trying to access a child node. 

![img_0987](https://user-images.githubusercontent.com/229352/38257353-f8d15422-3757-11e8-8f66-db87079c96a0.PNG)

**Comment by hosseinamin** [comment]
Fixed
