### ISSUE TITLE
iOS - cancel on edit screen?

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#50]
Not sure how we should implement this. Any ideas? 

(Maybe when edit - remove cog - and replace with play symbol (play))

**Comment by hosseinamin** [comment]
I'm not sure what do you mean, Can you elaborate?

**Comment by willwade** [comment]
I think I have found the problem.

The web shows the cancel button..

<img width="899" alt="screen shot 2018-04-10 at 18 04 53" src="https://user-images.githubusercontent.com/229352/38571936-ba0f91b2-3ce9-11e8-8971-487608cf3655.png">


The iOS app doesnt:

![img_1018](https://user-images.githubusercontent.com/229352/38572015-e102dc70-3ce9-11e8-8193-727ae5712729.jpg)

**Comment by hosseinamin** [comment]
i see, will fix

**Comment by hosseinamin** [comment]
i will remove cog on edit...
