### ISSUE TITLE
Sticky/Laggy/Slow to respond at times? 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#54]
Have a look at the below video.
https://www.dropbox.com/s/cvpqe8t2kr88uon/StickyPasco.mov?dl=0

When it runs it sometimes feels like there is a bit of a lag when selecting items? What do you think? 

Will

**Comment by hosseinamin** [comment]
Responsive voice library is working with an online server. There's delay for that to speak and then shows items bellow it.
1. I can remove must wait for speech. 
2. Or we can leave it as is.

I think first item lag is still there. I will try to fix that.

**Comment by willwade** [comment]
2. Leave it for now
