### ISSUE TITLE
Very quiet on iOS 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#57]
On the iOS build it’s really quiet even at full volume

**Comment by hosseinamin** [comment]
I could raise volume for cue voice. And it's working fine in my iPad. @willwade Can you make sure cue voice volume is doing nothing?

**Comment by willwade** [comment]
Ok. I think I've figured it out

If:

1. There is no headphone plugged in and
2. It doesn't have the checkbox ticked "Override to speaker" 

Then the maximum volume - cue or main  - is really quiet. I'm not sure how much of a bug this is - I guess it is but not sure what we can do about it.
