### ISSUE TITLE
Previous items indicator

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#59]
I like the way we now have one arrow to the left when there is a previous tree but two small tweaks (hopefully Small!)
- can we make the colour of the arrow  themable. I think we may want it to be a lighter colour
- the previous indicator - can that a less than symbol at the left ? Eg https://www.dropbox.com/s/zmgtsp0tv3xo4a9/IMG_1032.jpg?dl=0

**Comment by hosseinamin** [comment]
Is this issue still valid?

1. yes
2. image url is no longer available

**Comment by willwade** [comment]
Yes & No. I think there are some improvements generally about the UI of the tree. I was really trying to improve a visual cue that there is something further in the tree or something behind the current item in the tree. My mock-up wasnt great - so not to worried I lost that. This isn't urgent. 

1. Ok! 
2. I'll have a think more generally about this and mock some things up

**Comment by hosseinamin** [comment]
This is an old issue. I forgot all about it.
Here how you can change styles for that specific arrow.
Its icon is from fontawesome. It can be modified with css or javascript. 
```
/* just for the parent item */
#tree .current > .content > .arrow-wrp {
    color: red;
}
/* for all children of it */
#tree .current .content > .arrow-wrp {
    color: blue;
}
```

**Comment by willwade** [comment]
Fixed. just leaving Open for me to do something with this

**Comment by willwade** [comment]
Ok - I thought I was winning with that last commit.. But this screenshot explains my problem..

![Screenshot 2020-03-31 at 16 05 06](https://user-images.githubusercontent.com/229352/78042382-cf9aa400-7369-11ea-8694-77002a9630ac.png)

So want to style the one arrow that has the active parent item. Whats the css to do that?

**Comment by hosseinamin** [comment]
This change can fix it.
```
  #tree .current .content > .arrow-wrp { color: $theme-dark-child-arrow; font-size: 120%;transform: none;}
  #tree .current .content > .arrow-wrp { color: $theme-dark-child-arrow; font-size: 120%;transform: rotate(-180deg);}
```

**Comment by willwade** [comment]
Hmm. Somethings not right still. For me at least - it looks the same. 
<img width="726" alt="Screenshot 2020-04-01 at 09 59 51" src="https://user-images.githubusercontent.com/229352/78119192-f6a3b500-73ff-11ea-9af5-47256ba7f122.png">

**Comment by hosseinamin** [comment]
Found the issue, You need to swap these two lines to give precedence to parent arrow selection.
```
  #tree .current .content > .arrow-wrp { color: $theme-dark-child-arrow; font-size: 120%;transform: rotate(-180deg);}
 #tree .current .content > .arrow-wrp { color: $theme-dark-child-arrow; font-size: 120%;transform: none;}

```

**Comment by willwade** [comment]
Doing that the ``transform: rotate(-180deg);`` does nothing. 

Hmm. Let me explain - I think this might need some other css..

<img width="726" alt="landscape-1-level" src="https://user-images.githubusercontent.com/229352/78132874-62444d00-7415-11ea-86c1-2fea624c6495.png">
<img width="787" alt="landscape-2-level" src="https://user-images.githubusercontent.com/229352/78132883-640e1080-7415-11ea-93a3-cfea2d96d5a9.png">

and in smaller view
<img width="503" alt="small1" src="https://user-images.githubusercontent.com/229352/78132935-7be59480-7415-11ea-9bae-27ef7d158c57.png">
<img width="503" alt="small2" src="https://user-images.githubusercontent.com/229352/78132931-7ab46780-7415-11ea-97ec-7925513e242f.png">

I'm still not sure this is actually a *good* idea - but at least explains what I'm attempting.

**Comment by hosseinamin** [comment]
@willwade I've pushed a commit as an attempt to achieve this look. Take a look.
