### ISSUE TITLE
Alignment of selected items

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#68]
This is just a little distracting..

When going through options it starts with something like 
<img width="849" alt="screen shot 2018-04-25 at 18 12 20" src="https://user-images.githubusercontent.com/229352/39261480-807393dc-48b4-11e8-80bb-57fd4909ac53.png">

<img width="813" alt="screen shot 2018-04-25 at 18 12 48" src="https://user-images.githubusercontent.com/229352/39261479-805eecde-48b4-11e8-9b60-ef9036702eb4.png">

When selected the items that have been selected re-position themselves
<img width="891" alt="screen shot 2018-04-25 at 18 13 20" src="https://user-images.githubusercontent.com/229352/39261478-804760c8-48b4-11e8-8367-ab1017d20ef8.png">

Is there anyway to make everything fixed in that horizontal position when scanning through the items?

**Comment by hosseinamin** [comment]
I saw this issue. And fixed it. In which browser you're experiencing this issue?

**Comment by willwade** [comment]
In the iOS app

**Comment by hosseinamin** [comment]
fix for this issue is in commit https://github.com/AceCentre/pasco/commit/b3a094ac2fc2a074382fccb51101238393a1c145#diff-20af0266d0281a9270b2139d42dfc5d9R665

**Comment by willwade** [comment]
Yep. Pretty sure we can close this. Must check on iPad first
