### ISSUE TITLE
Settings title not in L10n 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#71]
Small bug - but the settings heading doesnt seem to be getting converted when changing langauge

**Comment by hosseinamin** [comment]
https://github.com/AceCentre/pasco/blob/master/html/edit-config.html#L12
Settings title has tag, `x-l10n="config_title"` meaning for translating it, key will be , `config_title`.
```
{ ...
  "config_title": "new text"
... }
```

**Comment by willwade** [comment]
See latest commit. I'm not sure its coming through..

**Comment by willwade** [comment]
Got it. I didnt have "Settings" in the file
