### ISSUE TITLE
Bug on startup. Can’t find tree

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#72]
If you load up the app and haven’t before you get the quick wizard. The only problem is you get an error saying it couldn’t locate the default tree.

**Comment by willwade** [comment]
Interestingly got this error on the iOS app today.. 
![img_1108](https://user-images.githubusercontent.com/229352/39581252-0a36d9ec-4ee3-11e8-8564-a012b4d9e4e5.png) - in the normal config screen

**Comment by hosseinamin** [comment]
Is this error only exists for "Spell_by_blocks_in_Frequency.md"?

**Comment by willwade** [comment]
I think so.. Im a bit worried about the startup error on iOS - I'm sure it was for the "default" one but could be wrong

**Comment by hosseinamin** [comment]
I can't re-create error about default tree. Is there steps to perform for getting this error again?

**Comment by willwade** [comment]
Yeah I cant replicate it. Lets close this for now
