### ISSUE TITLE
second screen functionality 

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#83]
SEnd selected text /letters to a second screen. Nb. Can’t be over tcp/ip. ?bt-le.

**Comment by hosseinamin** [comment]
html5 has websocket api as an alternative to tcp/ip.
[WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) is also available. Which can help connecting peers behind firewall and eliminate the need to setup a server.

**Comment by willwade** [comment]
The problem though is the second device needs to be incredibly easy to use. Turn on and receive. And low power. And small. I’m thinking a raspberry pi with one of these MissBirdler 1602 16x2 Character LCD Display Module HD44780 Blue BL for Arduino Raspberry pi https://www.amazon.co.uk/dp/B01M4R0NSD/ref=cm_sw_r_cp_api_MEFOBb81XEHFY  and itself running a nodejs service listening for any incoming chirp eg https://developers.chirp.io - and pasco sending chirp out.

**Comment by hosseinamin** [comment]
No problem. I think WebRTC is a good candidate.

**Comment by hosseinamin** [comment]
Specially if it support. local connection lookup and ip6

**Comment by willwade** [comment]
Re: #161 #137 #136

**Comment by gavinhenderson** [comment]
Closing in favour of #246
