### ISSUE TITLE
Help file to look better. Needs videos in it

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#85]
- [ ] Videos need a way of displaying nicely. Modal? 
- [ ] Thinking of a TOC - something like this: http://projects.jga.me/toc/#toc5

**Comment by hosseinamin** [comment]
> Will need to allow help file to be multilingual. Eg help-en.html help-pt.html etc?

This is how it should get translated. Simplest solution would be to list these files within a javascript file `help.js`. Which is simply support on web and iOS version.

**Comment by willwade** [comment]
Just remembered - not currently working on iOS build
