### ISSUE TITLE
Not sure how to use import

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#94]
So I can export a package - but import?

This is my file - with language file and mp3 files. In iOS I import this but I get a weird MacOS file line in the tree edit window.. 

Is there a folder convention I should be using? 

Zip file: https://www.dropbox.com/s/3eo29gvtfjc5wah/Archive.zip?dl=0

**Comment by hosseinamin** [comment]
Yes. I did applied a specific order. At the moment, all files should be in  a folder called `default`.
And `default/anyname.md` will be the tree file.
I did review my code again. I think multilingual support is not in import function.

**Comment by willwade** [comment]
Ok. Great thanks.

**Comment by willwade** [comment]
Does ﻿﻿https://www.dropbox.com/s/kc8de1jqkbl95bd/default.zip?dl=0 work for you? (I've also tried default/default/joke.md but thats not working either: https://www.dropbox.com/s/hxolz08jrc1a7v8/default2.zip?dl=0 )

**Comment by hosseinamin** [comment]
Are you testing in web version? Currently blob files are not support for web. It should work on iOS.

**Comment by willwade** [comment]
Its iOS Im struggling on. Its saying there is a parse error (or similar)

**Comment by hosseinamin** [comment]
So there should be a bug there. I have to test it. Is it urgent?

**Comment by willwade** [comment]
no - not urgent. thanks!
