### ISSUE TITLE
Bug: Recorded sounds not playing on Safari on iOS

### ISSUE THREAD

**Issue by willwade** [AceCentre/pasco#97]
Low-priority this - but spotted today. Im guessing its actually causing a error/break because all functionality stops when you try and play an audio file

**Comment by hosseinamin** [comment]
I think i know what is causing this issue. Safari does not support playing audio without user interaction like tap or keypress. Even though it is happening for initiation of audio playback.
But apparently play is not called in the same event cycle. Thus results audio to not play. And i audio promise will not get resolved, Everything hangs.

Fix for it is tricky. I can do it....

**Comment by willwade** [comment]
Ok. Don’t rush to fix this. On iOS the app is what people should be using. Just leave it open for now

**Comment by hosseinamin** [comment]
Is this on iOS Safari? Recording and importing audio files currently should only work on the iOS app (cordova based).

**Comment by willwade** [comment]
Yes. Note I’m referring to playing recorded sounds. Not recording them :)
